#pragma once

#define ID_MUTEX_COFFEE_MANAGER			"ID_MUTEX_COFFEE_MANAGER"
#define ID_MUTEX_COFFEE_LOGIN			"ID_MUTEX_COFFEE_LOGIN"
#define ID_MUTEX_COFFEE_PROCESS_MONITOR "ID_MUTEX_COFFEE_PROCESS_MONITOR"
#define ID_MUTEX_COFFEE_TRAY			"ID_MUTEX_COFFEE_TRAY"
